
services:
  web:
    build: .
    ports:
      - "80:80"  
    environment:
      - NODE_ENV=production  
    volumes:
      - .:/app                # Mount current directory
      - /app/node_modules     # Avoid overwriting node_modules
    restart: unless-stopped
