services:
  web:
    image: ubongpr7/facebook_camp_f:latest
    ports:
      - "80:80"  
    environment:
      - NODE_ENV=development 
    volumes:
      - .:/app               
      - /app/node_modules    
    command: ["yarn", "dev"] 
    restart: unless-stopped

