FROM node:22-bookworm-slim

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

RUN corepack enable

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY . .

EXPOSE 3000

CMD ["yarn", "next", "dev", "-H", "0.0.0.0", "-p", "3000"]
