
useEffect(() => {
    if (accessToken && userID) {
        
        fetchAdAccounts(accessToken).then((accounts) => {
          if (accounts) {
            
            console.log("Ad Accounts:", accounts);
          } else {
            console.log("Failed to fetch ad accounts.");
          }
});


    }
  }, [accessToken, userID]);



  
// import "./globals.css"
// import type { Metadata } from "next";
// import StoreProvider  from "@/redux/provider";

// export const metadata: Metadata = {
//   title: "Quick Campaign",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//       >
//         <StoreProvider>
//           {children}
//         </StoreProvider>
//       </body>
//     </html>
//   );
// }

