// createAdSet: builder.mutation({
//     query: ({
//         ad_creative_description,
//         ad_creative_headline,
//         ad_creative_primary_text,
//         ad_format,
//         attribution_setting,
//         audience_network,
//         call_to_action,
//         destination_url,
//         facebook,
//         facebook_reels,
//         feeds,
//         gender,
//         instagram,
//         instagram_feeds,
//         instagram_profile_feed,
//         instagram_reels,
//         instagram_search,
//         instagram_stories,
//         native_banner_interstitial,
//         rewarded_videos,
//         url_parameters
//     }) => ({
//         url: `/${ads_manager_api}/debug-adset/`,
//         method: "POST",
//         body: {
//             ad_creative_description,
//             ad_creative_headline,
//             ad_creative_primary_text,
//             ad_format,
//             attribution_setting,
//             audience_network,
//             call_to_action,
//             destination_url,
//             facebook,
//             facebook_reels,
//             feeds,
//             gender,
//             instagram,
//             instagram_feeds,
//             instagram_profile_feed,
//             instagram_reels,
//             instagram_search,
//             instagram_stories,
//             native_banner_interstitial,
//             rewarded_videos,
//             url_parameters
//         },
//     }),
// }),
