import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "../redux/provider";
import DashboardHeader from "../components/wrapper/dashboardHeader";
import NextTopLoader from 'nextjs-toploader';
export const metadata: Metadata = {
  title: "Intera Inventory",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   

  return (
    <html lang="en" suppressHydrationWarning>
      
      <body suppressHydrationWarning>
      <NextTopLoader />
        <StoreProvider>
        <DashboardHeader>
        {children}
        </DashboardHeader>
        </StoreProvider>
        
      </body>
    </html>
  );
}

