import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "@/redux/provider";
// import {getCookie,setCookie} from 'cookies-next'
// import TokenRefresh from "@/utils/refreshAuthClient";
// import AuthChecker from "@/utils/checktokenClient";

export const metadata: Metadata = {
  title: "Quick Campaign",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   

  return (
    <html lang="en">
      <body>
        <StoreProvider>
        
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}

