
import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "@/redux/provider";
import { useTokenRefresh } from "@/utils/refreshAuth"; 



export const metadata: Metadata = {
  title: "Quick Campaign",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useTokenRefresh(); 

  return (
    <html lang="en">
      <body>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}


// import "./globals.css"
// import type { Metadata } from "next";
// import StoreProvider  from "@/redux/provider";

// export const metadata: Metadata = {
//   title: "Quick Campaign",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//       >
//         <StoreProvider>
//           {children}
//         </StoreProvider>
//       </body>
//     </html>
//   );
// }

